[book]
authors = ["drmin"]
language = "en"
multilingual = false
src = "src"
title = "learn_rust"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.playground]
editable = true

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
